// Code generated by Shopee API Generator. DO NOT EDIT.
package goshopee

type AccountHealthService interface {
	// GetShopPerformance The data metrics of shop performance.
	//
	// https://open.shopee.com/documents/v2/v2.account_health.get_shop_performance?module=103&type=1
	GetShopPerformance(sid uint64, tok string) (*GetShopPerformanceResponse, error)
	// GetMetricSourceDetail Get the Affected Orders / Relevant Listings / Relevant Violations details of metrics.
	// https://open.shopee.com/documents/v2/v2.account_health.get_metric_source_detail?module=103&type=1
	GetMetricSourceDetail(sid uint64, opt GetMetricSourceDetailRequest, tok string) (*GetMetricSourceDetailResponse, error)
	// GetPenaltyPointHistory Get the penalty point records generated in the current quarter.
	// https://open.shopee.com/documents/v2/v2.account_health.get_penalty_point_history?module=103&type=1
	GetPenaltyPointHistory(sid uint64, opt GetPenaltyPointHistoryRequest, tok string) (*GetPenaltyPointHistoryResponse, error)
	// GetPunishmentHistory Get the punishment records generated in the current quarter.
	// https://open.shopee.com/documents/v2/v2.account_health.get_punishment_history?module=103&type=1
	GetPunishmentHistory(sid uint64, opt GetPunishmentHistoryRequest, tok string) (*GetPunishmentHistoryResponse, error)
	// GetListingsWithIssues Get the Problematic Listings to improve the listings to avoid incurring penalty points.
	// https://open.shopee.com/documents/v2/v2.account_health.get_listings_with_issues?module=103&type=1
	GetListingsWithIssues(sid uint64, opt GetListingsWithIssuesRequest, tok string) (*GetListingsWithIssuesResponse, error)
	// GetLateOrders Get the Late Orders to take action to avoid order cancellation and penalty points.
	// https://open.shopee.com/documents/v2/v2.account_health.get_late_orders?module=103&type=1
	GetLateOrders(sid uint64, opt GetLateOrdersRequest, tok string) (*GetLateOrdersResponse, error)
}

type AccountHealthServiceOp struct {
	client *Client
}

func (s *AccountHealthServiceOp) GetShopPerformance(sid uint64, tok string) (*GetShopPerformanceResponse, error) {
	path := "/account_health/get_shop_performance"
	resp := new(GetShopPerformanceResponse)
	err := s.client.WithShop(sid, tok).Get(path, resp, nil)
	return resp, err
}

func (s *AccountHealthServiceOp) GetMetricSourceDetail(sid uint64, opt GetMetricSourceDetailRequest, tok string) (*GetMetricSourceDetailResponse, error) {
	path := "/account_health/get_metric_source_detail"
	resp := new(GetMetricSourceDetailResponse)
	err := s.client.WithShop(sid, tok).Get(path, resp, opt)
	return resp, err
}

func (s *AccountHealthServiceOp) GetPenaltyPointHistory(sid uint64, opt GetPenaltyPointHistoryRequest, tok string) (*GetPenaltyPointHistoryResponse, error) {
	path := "/account_health/get_penalty_point_history"
	resp := new(GetPenaltyPointHistoryResponse)
	err := s.client.WithShop(sid, tok).Get(path, resp, opt)
	return resp, err
}

func (s *AccountHealthServiceOp) GetPunishmentHistory(sid uint64, opt GetPunishmentHistoryRequest, tok string) (*GetPunishmentHistoryResponse, error) {
	path := "/account_health/get_punishment_history"
	resp := new(GetPunishmentHistoryResponse)
	err := s.client.WithShop(sid, tok).Get(path, resp, opt)
	return resp, err
}

func (s *AccountHealthServiceOp) GetListingsWithIssues(sid uint64, opt GetListingsWithIssuesRequest, tok string) (*GetListingsWithIssuesResponse, error) {
	path := "/account_health/get_listings_with_issues"
	resp := new(GetListingsWithIssuesResponse)
	err := s.client.WithShop(sid, tok).Get(path, resp, opt)
	return resp, err
}

func (s *AccountHealthServiceOp) GetLateOrders(sid uint64, opt GetLateOrdersRequest, tok string) (*GetLateOrdersResponse, error) {
	path := "/account_health/get_late_orders"
	resp := new(GetLateOrdersResponse)
	err := s.client.WithShop(sid, tok).Get(path, resp, opt)
	return resp, err
}
