// Code generated by Shopee API Generator. DO NOT EDIT.
package goshopee

type FBSService interface {
	// QueryBrShopEnrollmentStatus This API checks whether a given shop_id is eligible to enroll in the Brazil Fulfilled-by-Shopee (FBS) service.
	// https://open.shopee.com/documents/v2/v2.fbs.query_br_shop_enrollment_status?module=126&type=1
	QueryBrShopEnrollmentStatus(sid uint64, tok string) (*QueryBrShopEnrollmentStatusResponse, error)
	// QueryBrShopInvoiceError This API handles failed invoice issuance for FBS-related processes, covering Inbound Requests, RTS Requests, Sales Orders, and Move Transfer Orders.
	// https://open.shopee.com/documents/v2/v2.fbs.query_br_shop_invoice_error?module=126&type=1
	QueryBrShopInvoiceError(sid uint64, req QueryBrShopInvoiceErrorRequest, tok string) (*QueryBrShopInvoiceErrorResponse, error)
	// QueryBrShopBlockStatus This API checks whether an FBS shop is blocked due to invoice-related issues. When blocked, the shop cannot create new Inbound Requests, and its warehouse inventory is restricted from being sold.
	// https://open.shopee.com/documents/v2/v2.fbs.query_br_shop_block_status?module=126&type=1
	QueryBrShopBlockStatus(sid uint64, tok string) (*QueryBrShopBlockStatusResponse, error)
	// QueryBrSkuBlockStatus This API checks whether an FBS product is blocked due to invoice-related issues. When blocked, the product cannot be included in new Inbound Requests, and its warehouse inventory is restricted from being sold.
	// https://open.shopee.com/documents/v2/v2.fbs.query_br_sku_block_status?module=126&type=1
	QueryBrSkuBlockStatus(sid uint64, req QueryBrSkuBlockStatusRequest, tok string) (*QueryBrSkuBlockStatusResponse, error)
}

type FBSServiceOp struct {
	client *Client
}

func (s *FBSServiceOp) QueryBrShopEnrollmentStatus(sid uint64, tok string) (*QueryBrShopEnrollmentStatusResponse, error) {
	path := "/fbs/query_br_shop_enrollment_status"
	resp := new(QueryBrShopEnrollmentStatusResponse)
	err := s.client.WithShop(sid, tok).Post(path, nil, resp)
	return resp, err
}

func (s *FBSServiceOp) QueryBrShopInvoiceError(sid uint64, req QueryBrShopInvoiceErrorRequest, tok string) (*QueryBrShopInvoiceErrorResponse, error) {
	path := "/fbs/query_br_shop_invoice_error"
	resp := new(QueryBrShopInvoiceErrorResponse)
	err := s.client.WithShop(sid, tok).Post(path, req, resp)
	return resp, err
}

func (s *FBSServiceOp) QueryBrShopBlockStatus(sid uint64, tok string) (*QueryBrShopBlockStatusResponse, error) {
	path := "/fbs/query_br_shop_block_status"
	resp := new(QueryBrShopBlockStatusResponse)
	err := s.client.WithShop(sid, tok).Post(path, nil, resp)
	return resp, err
}

func (s *FBSServiceOp) QueryBrSkuBlockStatus(sid uint64, req QueryBrSkuBlockStatusRequest, tok string) (*QueryBrSkuBlockStatusResponse, error) {
	path := "/fbs/query_br_sku_block_status"
	resp := new(QueryBrSkuBlockStatusResponse)
	err := s.client.WithShop(sid, tok).Post(path, req, resp)
	return resp, err
}
